### ISSUE TITLE
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

### ISSUE THREAD

**Issue by Hellrunner2k** [hnmr293/sd-webui-evviz2#3]
Traceback (most recent call last):
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-evviz2\scripts\evviz2.py", line 361, in f
v = fn(*args, **kwargs)
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-evviz2\scripts\evviz2.py", line 338, in run
k = mod.to_k(context._context)
File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "C:\AI\stable-diffusion-webui\extensions-builtin\Lora\networks.py", line 361, in network_Linear_forward
return torch.nn.Linear_forward_before_network(self, input)
File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'

I'm getting this when I "run"

GTX 1070

**Comment by Hellrunner2k** [comment]
Traceback (most recent call last):
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-evviz2\scripts\evviz2.py", line 361, in f
v = fn(*args, **kwargs)
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-evviz2\scripts\evviz2.py", line 323, in run
tokens, context = generate_embeddings(te, prompt, padding)
File "C:\AI\stable-diffusion-webui\extensions\sd-webui-evviz2\scripts\evviz2.py", line 100, in generate_embeddings
embeddings = te(prompts).cpu()
File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "C:\AI\stable-diffusion-webui\modules\sd_hijack_clip.py", line 234, in forward
z = self.process_tokens(tokens, multipliers)
File "C:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-gradients\aesthetic_clip.py", line 202, in __call__
z = self.process_tokens(remade_batch_tokens, multipliers)
File "C:\AI\stable-diffusion-webui\modules\sd_hijack_clip.py", line 271, in process_tokens
z = self.encode_with_transformers(tokens)
File "C:\AI\stable-diffusion-webui\modules\sd_hijack_clip.py", line 324, in encode_with_transformers
outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
result = forward_call(*args, **kwargs)
File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 811, in forward
return self.text_model(
File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 721, in forward
encoder_outputs = self.encoder(
File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 650, in forward
layer_outputs = encoder_layer(
File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 378, in forward
hidden_states = self.layer_norm1(hidden_states)
File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
return forward_call(*args, **kwargs)
File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\normalization.py", line 190, in forward
return F.layer_norm(
File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\torch\nn\functional.py", line 2515, in layer_norm
return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Float but found Half

i made an update to all extensions

**Comment by hnmr293** [comment]
Thank you for your feedback.
I've tried to fix it. Update this extension.

Please enable this checkbox.
![image](https://github.com/hnmr293/sd-webui-evviz2/assets/120772120/aeb57f94-d0e6-4d8f-83fd-f21f25e337e6)

But unfortunately I couldn't reproduce your errors.
So please let me know if your problem has been fixed.
